# Generated by Django 4.0.1 on 2022-03-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryAdditionalElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активная?"),
                ),
            ],
            options={
                "verbose_name": "категория дополнительных элементов",
                "verbose_name_plural": "категории дополнительных элементов",
            },
        ),
        migrations.CreateModel(
            name="CategoryBodyComplectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активная?"),
                ),
            ],
            options={
                "verbose_name": "категория комплектации корпуса",
                "verbose_name_plural": "категории комплектации корпусов",
            },
        ),
        migrations.CreateModel(
            name="ClosetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="тип шкафа",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активный?"),
                ),
            ],
            options={
                "verbose_name": "Тип шкафа",
                "verbose_name_plural": "Типы шкафов",
            },
        ),
        migrations.CreateModel(
            name="DoorsSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активная?"),
                ),
            ],
            options={
                "verbose_name": "система дверей",
                "verbose_name_plural": "системы дверей",
            },
        ),
        migrations.CreateModel(
            name="FillingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активный?"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_filling_scheme",
                        to="closet.closettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема наполнения",
                "verbose_name_plural": "Схемы наполнения",
            },
        ),
        migrations.CreateModel(
            name="DoorsProfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/doors/profile/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doors_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doors_system_doors_profiles",
                        to="closet.doorssystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "дверной профиль",
                "verbose_name_plural": "дверные профили",
            },
        ),
        migrations.CreateModel(
            name="DoorsMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название материала",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/doors/materials/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filling_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filling_scheme_doors_materials",
                        to="closet.fillingscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "материал дверей",
                "verbose_name_plural": "материалы дверей",
            },
        ),
        migrations.CreateModel(
            name="DoorsColours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/doors/colour/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doors_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doors_system_doors_colours",
                        to="closet.doorssystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "цвет дверей",
                "verbose_name_plural": "цвета дверей",
            },
        ),
        migrations.CreateModel(
            name="Doorhandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/doors/handle/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doors_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doors_system_doorhandle",
                        to="closet.doorssystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "дверная ручка",
                "verbose_name_plural": "дверные ручки",
            },
        ),
        migrations.CreateModel(
            name="Dimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_width", models.IntegerField(verbose_name="Минимальная ширина")),
                ("max_width", models.IntegerField(verbose_name="Максимальная ширина")),
                ("min_length", models.IntegerField(verbose_name="Минимальная длина")),
                ("max_length", models.IntegerField(verbose_name="Максимальная длина")),
                ("min_depth", models.IntegerField(verbose_name="Минимальная глубина")),
                ("max_depth", models.IntegerField(verbose_name="Максимальная глубина")),
                (
                    "filling_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filling_scheme_dimensions",
                        to="closet.fillingscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер шкафа",
                "verbose_name_plural": "Размеры шкафов",
            },
        ),
        migrations.CreateModel(
            name="BodyComplectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение",
                        upload_to="planner/complectation/%Y/%m/%d",
                        verbose_name="Фото элемента'",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_body_complectation",
                        to="closet.categorybodycomplectation",
                    ),
                ),
            ],
            options={
                "verbose_name": "комплектация корпуса",
                "verbose_name_plural": "комплектация корпусов",
            },
        ),
        migrations.CreateModel(
            name="BodyColour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="configurator/default.jpg",
                        help_text="Загрузите изображение",
                        upload_to="configurator/body/%Y/%m/%d",
                        verbose_name="Фото цвета",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                (
                    "filling_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filling_scheme_image",
                        to="closet.fillingscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет корпуса",
                "verbose_name_plural": "Цвета корпусов",
            },
        ),
        migrations.CreateModel(
            name="AdditionalElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение",
                        upload_to="planner/additional_elements/%Y/%m/%d",
                        verbose_name="Фото элемента'",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_additional_elements",
                        to="closet.categoryadditionalelements",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительный элемент",
                "verbose_name_plural": "дополнительные элементы",
            },
        ),
    ]
