# Generated by Django 4.0.1 on 2022-03-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimensions",
            name="max_length",
        ),
        migrations.RemoveField(
            model_name="dimensions",
            name="min_length",
        ),
        migrations.AddField(
            model_name="dimensions",
            name="max_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Максимальная высота"
            ),
        ),
        migrations.AddField(
            model_name="dimensions",
            name="min_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Минимальная высота"
            ),
        ),
        migrations.AlterField(
            model_name="fillingscheme",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активная?"),
        ),
        migrations.AlterField(
            model_name="fillingscheme",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_filling_scheme",
                to="closet.closettype",
                verbose_name="тип",
            ),
        ),
    ]
