# Generated by Django 4.0.1 on 2022-03-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0002_remove_dimensions_max_length_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodycolour",
            options={
                "verbose_name": "Цвет корпуса",
                "verbose_name_plural": "Цвета корпуса",
            },
        ),
        migrations.AddField(
            model_name="bodycomplectation",
            name="filling_scheme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filling_scheme_body_complectation",
                to="closet.fillingscheme",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dimensions",
            name="max_height",
            field=models.IntegerField(default=1, verbose_name="Максимальная высота"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dimensions",
            name="min_height",
            field=models.IntegerField(default=1, verbose_name="Минимальная высота"),
            preserve_default=False,
        ),
    ]
