# Generated by Django 4.0.1 on 2022-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_alter_bodycolour_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodycomplectation",
            options={
                "verbose_name": "комплектация корпуса",
                "verbose_name_plural": "комплектация корпуса",
            },
        ),
        migrations.RemoveField(
            model_name="bodycomplectation",
            name="category",
        ),
        migrations.AddField(
            model_name="bodycomplectation",
            name="category",
            field=models.ManyToManyField(
                related_name="category_body_complectation",
                to="closet.CategoryBodyComplectation",
                verbose_name="категория",
            ),
        ),
    ]
