# Generated by Django 4.0.1 on 2022-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0004_alter_bodycomplectation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodycomplectation",
            name="filling_scheme",
        ),
        migrations.AddField(
            model_name="bodycomplectation",
            name="filling_scheme",
            field=models.ManyToManyField(
                related_name="filling_scheme_body_complectation",
                to="closet.FillingScheme",
                verbose_name="схема наполнения",
            ),
        ),
    ]
