# Generated by Django 4.0.1 on 2022-03-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0005_remove_bodycomplectation_filling_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodycomplectation",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Пожалуйста, добавьте альтернативный текст",
                max_length=255,
                null=True,
                verbose_name="Альтернативный текст",
            ),
        ),
        migrations.RemoveField(
            model_name="bodycolour",
            name="filling_scheme",
        ),
        migrations.AddField(
            model_name="bodycolour",
            name="filling_scheme",
            field=models.ManyToManyField(
                related_name="filling_scheme_image",
                to="closet.FillingScheme",
                verbose_name="схема наполнения",
            ),
        ),
    ]
