# Generated by Django 4.0.1 on 2022-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0006_bodycomplectation_alt_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalelements",
            name="filling_scheme",
            field=models.ManyToManyField(
                related_name="filling_scheme_additional_elements",
                to="closet.FillingScheme",
                verbose_name="схема наполнения",
            ),
        ),
        migrations.RemoveField(
            model_name="additionalelements",
            name="category",
        ),
        migrations.AddField(
            model_name="additionalelements",
            name="category",
            field=models.ManyToManyField(
                related_name="category_additional_elements",
                to="closet.CategoryAdditionalElements",
                verbose_name="категория",
            ),
        ),
    ]
