# Generated by Django 4.0.1 on 2022-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0007_additionalelements_filling_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalelements",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Пожалуйста, добавьте альтернативный текст",
                max_length=255,
                null=True,
                verbose_name="Альтернативный текст",
            ),
        ),
    ]
