# Generated by Django 4.0.1 on 2022-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0008_additionalelements_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="doorssystem",
            name="filling_scheme",
            field=models.ManyToManyField(
                related_name="filling_scheme_doors_system",
                to="closet.FillingScheme",
                verbose_name="схема наполнения",
            ),
        ),
        migrations.RemoveField(
            model_name="doorsmaterials",
            name="filling_scheme",
        ),
        migrations.AddField(
            model_name="doorsmaterials",
            name="filling_scheme",
            field=models.ManyToManyField(
                related_name="filling_scheme_doors_materials",
                to="closet.FillingScheme",
                verbose_name="схема наполнения",
            ),
        ),
    ]
