# Generated by Django 4.0.1 on 2022-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0009_doorssystem_filling_scheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doorsmaterials",
            name="filling_scheme",
        ),
        migrations.AddField(
            model_name="doorsmaterials",
            name="doors_system",
            field=models.ManyToManyField(
                related_name="doors_system_doors_materials",
                to="closet.DoorsSystem",
                verbose_name="система дверей",
            ),
        ),
        migrations.AlterField(
            model_name="closettype",
            name="type",
            field=models.CharField(
                help_text="Обязательное и уникальное поле",
                max_length=255,
                unique=True,
                verbose_name="количество дверей",
            ),
        ),
        migrations.RemoveField(
            model_name="doorhandle",
            name="doors_system",
        ),
        migrations.AddField(
            model_name="doorhandle",
            name="doors_system",
            field=models.ManyToManyField(
                related_name="doors_system_doorhandle",
                to="closet.DoorsSystem",
                verbose_name="система дверей",
            ),
        ),
        migrations.RemoveField(
            model_name="doorsprofiles",
            name="doors_system",
        ),
        migrations.AddField(
            model_name="doorsprofiles",
            name="doors_system",
            field=models.ManyToManyField(
                related_name="doors_system_doors_profiles",
                to="closet.DoorsSystem",
                verbose_name="система дверей",
            ),
        ),
        migrations.DeleteModel(
            name="DoorsColours",
        ),
    ]
