# Generated by Django 4.0.1 on 2022-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0010_remove_doorsmaterials_filling_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doorssystem",
            name="position",
            field=models.IntegerField(null=True, verbose_name="Позиция на сайте"),
        ),
    ]
