# Generated by Django 4.0.1 on 2022-01-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("-user",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="profile",
            name="apartment",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, help_text="Not Required", verbose_name="квартира"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="building",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, help_text="Not Required", verbose_name="корпус"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="house",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, help_text="Not Required", verbose_name="дом"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Not Required",
                max_length=255,
                verbose_name="улица",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="town",
            field=models.CharField(
                blank=True,
                help_text="Not Required",
                max_length=255,
                verbose_name="город",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
