# Generated by Django 4.0.1 on 2022-01-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_alter_profile_options_remove_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("-user",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="apartment",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Not Required", null=True, verbose_name="квартира"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="building",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Not Required", null=True, verbose_name="корпус"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="house",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Not Required", null=True, verbose_name="дом"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Not Required",
                max_length=255,
                null=True,
                verbose_name="улица",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="town",
            field=models.CharField(
                blank=True,
                help_text="Not Required",
                max_length=255,
                null=True,
                verbose_name="город",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
