# Generated by Django 4.0.1 on 2022-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_options_alter_profile_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(default=1, max_length=50, verbose_name="тел"),
            preserve_default=False,
        ),
    ]
