# Generated by Django 4.0.1 on 2022-01-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="product_type",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
    ]
