# Generated by Django 4.0.1 on 2022-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_product_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products_category",
                to="shop.Category",
                verbose_name="категория",
            ),
        ),
    ]
