# Generated by Django 4.0.1 on 2022-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Изменить видимость товара",
                verbose_name="Видимость товара",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/default.jpg",
                help_text="Загрузите изображение товара",
                upload_to="products/%Y/%m/%d",
                verbose_name="Изображение",
            ),
        ),
    ]
