# Generated by Django 4.0.1 on 2022-01-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_is_active_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop.productspecification",
                verbose_name="Свойство",
            ),
        ),
    ]
