# Generated by Django 4.0.1 on 2022-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_productspecificationvalue_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                error_messages={
                    "name": {
                        "max_length": "Цена должна быть в диапазоне от 0 до 9 999 999.99."
                    }
                },
                help_text="Maximum 9 999 999.99",
                max_digits=9,
                null=True,
                verbose_name="обычная цена",
            ),
        ),
    ]
