# Generated by Django 4.0.1 on 2022-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_regular_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecification",
            name="category",
            field=models.ManyToManyField(
                related_name="products_specification_category",
                to="shop.Category",
                verbose_name="категория",
            ),
        ),
    ]
