# Generated by Django 4.0.1 on 2022-01-12 12:42

import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_productspecification_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecification",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="category",
            field=mptt.fields.TreeManyToManyField(
                related_name="products_specification_category",
                to="shop.Category",
                verbose_name="категория",
            ),
        ),
    ]
