# Generated by Django 4.0.1 on 2022-01-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_productspecification_level_productspecification_lft_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productspecification",
            old_name="category",
            new_name="parent",
        ),
    ]
