# Generated by Django 4.0.1 on 2022-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rename_category_productspecification_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="level",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="tree_id",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="category",
            field=models.ManyToManyField(
                related_name="products_specification_category",
                to="shop.Category",
                verbose_name="категория",
            ),
        ),
    ]
