# Generated by Django 4.0.1 on 2022-01-12 14:19

import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_productspecification_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="category",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="lft",
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="parent",
            field=mptt.fields.TreeManyToManyField(
                blank=True, related_name="children_specification", to="shop.Category"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
