# Generated by Django 4.0.1 on 2022-01-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_productspecification_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='specification',
            field=models.ForeignKey(limit_choices_to={'category': 1}, on_delete=django.db.models.deletion.RESTRICT, to='shop.productspecification', verbose_name='Свойство'),
        ),
    ]
