# Generated by Django 4.0.1 on 2022-01-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_productspecificationvalue_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.productspecification', verbose_name='Свойство'),
        ),
    ]
