# Generated by Django 4.0.1 on 2022-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_productspecificationvalue_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Not Required", verbose_name="описание"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="for_main",
            field=models.BooleanField(default=False, verbose_name="для главной?"),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="planner/default.jpg",
                help_text="Загрузите изображение категории",
                upload_to="planner/shop/category/%Y/%m/%d",
                verbose_name="изображение",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Позиция на сайте"
            ),
        ),
    ]
