# Generated by Django 4.0.1 on 2022-09-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_category_description_category_for_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="position",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Позиция в категории"
            ),
        ),
    ]
