# Generated by Django 4.0.1 on 2022-09-08 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_color_colorprice_colorimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorprice",
            name="price_percent",
            field=models.IntegerField(
                default=0,
                help_text="Изменение цены товара за цвет в %",
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Добавленная стоимость в %",
            ),
        ),
    ]
