# Generated by Django 4.0.1 on 2022-09-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_colorprice_price_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorimage",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_image",
                to="shop.colorprice",
            ),
        ),
    ]
