# Generated by Django 4.0.1 on 2022-09-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_colorimage_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="products_dimensions_category",
                        to="shop.Category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер товара",
                "verbose_name_plural": "Размеры товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="colorprice",
            options={
                "verbose_name": "Изменение цены товара за цвет",
                "verbose_name_plural": "Изменение цен товаров за цвета",
            },
        ),
        migrations.AlterModelOptions(
            name="productspecification",
            options={
                "verbose_name": "Свойство товара",
                "verbose_name_plural": "Свойства товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="productspecificationvalue",
            options={
                "verbose_name": "Значение свойства товара",
                "verbose_name_plural": "Значения свойства товаров",
            },
        ),
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="value",
            field=models.CharField(
                help_text="Значение свойства товара (maximum of 255 words)",
                max_length=255,
                verbose_name="значение",
            ),
        ),
        migrations.CreateModel(
            name="DimensionsValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Значение размера товара в мм, для п.м. указывается ширина 1 п.м, для ДШВ - ДхШхВ, для ДШГ - ДхШхГ, для ДШ - ДхШ",
                        max_length=255,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="shop.dimensions",
                        verbose_name="Размеры",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение размера",
                "verbose_name_plural": "Значения размеров",
            },
        ),
        migrations.CreateModel(
            name="DimensionsPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_change",
                    models.IntegerField(
                        default=0,
                        help_text="Изменение цены товара от размер",
                        verbose_name="Изменение цены от размер",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение цены товара от размера",
                "verbose_name_plural": "Изменение цен товаров от размеров",
            },
        ),
    ]
