# Generated by Django 4.0.1 on 2022-09-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_dimensions_alter_colorprice_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimensionsprice",
            name="id",
        ),
        migrations.AlterField(
            model_name="dimensionsprice",
            name="price_change",
            field=models.IntegerField(
                default=0,
                help_text="Изменение цены товара от размеров",
                verbose_name="Изменение цены от размера",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionsprice",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="shop.dimensionsvalue",
            ),
        ),
    ]
