# Generated by Django 4.0.1 on 2022-09-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_remove_dimensionsprice_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimensionsvalue",
            options={
                "verbose_name": "Значение размера и изменение цены",
                "verbose_name_plural": "Значения размеров изменение цен",
            },
        ),
        migrations.AddField(
            model_name="dimensionsvalue",
            name="price_change",
            field=models.IntegerField(
                default=0,
                help_text="Изменение цены товара от размеров",
                verbose_name="Изменение цены от размера",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionsvalue",
            name="value",
            field=models.CharField(
                help_text="Значение размера товара в мм, для п.м. указывается ширина 1 п.м, для ШГВ - ШхГхВ, для ДШ - ДхШ",
                max_length=255,
                verbose_name="Значение",
            ),
        ),
        migrations.DeleteModel(
            name="DimensionsPrice",
        ),
    ]
