# Generated by Django 4.0.1 on 2022-11-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_alter_category_position_alter_categoryimage_for_main_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="is_feature",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="productimage",
            name="main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dimensionsvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimensions_value",
                to="shop.product",
            ),
        ),
    ]
