# Generated by Django 4.0.1 on 2023-01-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_remove_category_for_main_category_for_main_menu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="популярный товар"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                error_messages={
                    "name": {
                        "max_length": "Цена должна быть в диапазоне от 0 до 9 999 999.99."
                    }
                },
                help_text="Maximum 9 999 999.99",
                max_digits=9,
                null=True,
                verbose_name="Цена со скидкой",
            ),
        ),
    ]
