# Generated by Django 4.0.1 on 2022-05-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Обязательное",
                        max_length=255,
                        verbose_name="название материала",
                    ),
                ),
                ("text", models.TextField(verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/main/%Y/%m/%d",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="альтернативный текст",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="активно?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "О компании",
            },
        ),
        migrations.CreateModel(
            name="Examples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="название примера",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Not Required", verbose_name="описание"
                    ),
                ),
                (
                    "for_main",
                    models.BooleanField(default=False, verbose_name="для главной?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "пример работы",
                "verbose_name_plural": "примеры работ",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное",
                        max_length=255,
                        verbose_name="название вопроса",
                    ),
                ),
                ("question", models.TextField(verbose_name="вопрос")),
                ("answer", models.TextField(verbose_name="ответ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно?"),
                ),
                (
                    "for_main",
                    models.BooleanField(default=False, verbose_name="для главной?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
            },
        ),
        migrations.CreateModel(
            name="ExamplesPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обязательное и уникальное поле",
                        max_length=255,
                        unique=True,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение товара",
                        upload_to="planner/examples/%Y/%m/%d",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно?"),
                ),
                (
                    "examples",
                    models.ManyToManyField(
                        related_name="filling_scheme_image",
                        to="information.Examples",
                        verbose_name="пример",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
    ]
