# Generated by Django 4.0.1 on 2022-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcompany",
            options={"verbose_name": "О компании", "verbose_name_plural": "О компании"},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQ"},
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="title",
            field=models.CharField(
                help_text="Обязательное", max_length=255, verbose_name="заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="examplesphoto",
            name="examples",
            field=models.ManyToManyField(
                blank=True,
                related_name="filling_scheme_image",
                to="information.Examples",
                verbose_name="пример",
            ),
        ),
    ]
