# Generated by Django 4.0.1 on 2023-01-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0004_alter_mainpageheader_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpageheader",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Только одина активная шапка",
                null=True,
                unique=True,
                verbose_name="активно?",
            ),
        ),
    ]
