# Generated by Django 4.0.1 on 2023-01-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0005_alter_mainpageheader_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutcompany",
            name="image",
            field=models.ImageField(
                blank=True,
                default="planner/default.jpg",
                help_text="Загрузите изображение компании",
                upload_to="planner/main/%Y/%m/%d",
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="mainpageheader",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Допустима одна шапка в значении 'ДА', остальные - неизвестно",
                null=True,
                unique=True,
                verbose_name="активно?",
            ),
        ),
    ]
