# Generated by Django 4.0.1 on 2023-01-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0006_alter_aboutcompany_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Обязательное",
                        max_length=255,
                        verbose_name="заголовок",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="текст")),
                # ('is_active', models.BooleanField(blank=True, default=False, verbose_name='активно?')),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение планировщика",
                        upload_to="planner/main_page/%Y/%m/%d",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Планировщик на главной",
                "verbose_name_plural": "Планировщик на главной",
            },
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="image",
            field=models.ImageField(
                blank=True,
                default="planner/default.jpg",
                help_text="Загрузите изображение компании",
                upload_to="main_page/about_company/%Y/%m/%d",
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="examplesphoto",
            name="image",
            field=models.ImageField(
                blank=True,
                default="planner/default.jpg",
                help_text="Загрузите изображение товара",
                upload_to="work_examples/%Y/%m/%d",
                verbose_name="изображение",
            ),
        ),
    ]
