# Generated by Django 4.0.1 on 2023-01-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0007_planner_alter_aboutcompany_image_and_more"),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='planner',
    #         name='is_active',
    #         field=models.BooleanField(blank=True, default=None, help_text="Допустима одна шапка в значении 'ДА', остальные - неизвестно", null=True, verbose_name='активно?'),
    #     ),
    # ]
