# Generated by Django 4.0.1 on 2023-01-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0008_planner_is_active"),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='planner',
    #         name='is_active',
    #     ),
    # ]
