# Generated by Django 4.0.1 on 2023-01-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0009_remove_planner_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="planner",
            name="is_activef",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Допустима одна шапка в значении 'ДА', остальные - неизвестно",
                null=True,
                unique=True,
                verbose_name="активно?",
            ),
        ),
    ]
