# Generated by Django 4.0.1 on 2023-01-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0010_planner_is_activef"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planner",
            old_name="is_activef",
            new_name="is_active",
        ),
    ]
