# Generated by Django 4.0.1 on 2023-01-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0011_rename_is_activef_planner_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Planner",
        ),
    ]
