# Generated by Django 4.0.1 on 2023-01-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0012_delete_planner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Обязательное",
                        max_length=255,
                        verbose_name="заголовок",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="текст")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Допустима одна шапка в значении 'ДА', остальные - неизвестно",
                        null=True,
                        unique=True,
                        verbose_name="активно?",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="planner/default.jpg",
                        help_text="Загрузите изображение планировщика",
                        upload_to="planner/main_page/%Y/%m/%d",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Пожалуйста, добавьте альтернативный текст",
                        max_length=255,
                        null=True,
                        verbose_name="Альтернативный текст",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Планировщик на главной",
                "verbose_name_plural": "Планировщик на главной",
            },
        ),
    ]
