# Generated by Django 4.0.1 on 2023-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0013_planner"),
    ]

    operations = [
        migrations.AddField(
            model_name="examples",
            name="category",
            field=models.CharField(
                default="",
                help_text="Обязательное и уникальное поле",
                max_length=255,
                verbose_name="категория работ",
            ),
        ),
        migrations.AddField(
            model_name="examples",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                error_messages={
                    "name": {
                        "max_length": "Цена должна быть в диапазоне от 0 до 9 999 999.99."
                    }
                },
                help_text="Maximum 9 999 999.99",
                max_digits=9,
                null=True,
                verbose_name="цена",
            ),
        ),
    ]
