# Generated by Django 4.0.1 on 2023-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0016_alter_examplesphoto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesphoto",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="service_image",
                to="information.Services",
                verbose_name="фото услуги",
            ),
        ),
    ]
