# Generated by Django 4.0.1 on 2023-01-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0017_alter_servicesphoto_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesphoto",
            name="services",
        ),
        migrations.AddField(
            model_name="servicesphoto",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_photo",
                to="information.services",
                verbose_name="фото услуги",
            ),
        ),
    ]
