# Generated by Django 4.0.1 on 2023-01-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Пожалуйста, добавьте альтернативный текст",
                max_length=255,
                null=True,
                verbose_name="альтернативный текст",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="carousel_link_text",
            field=models.CharField(
                blank=True,
                default="ссылка",
                max_length=250,
                verbose_name="текст ссылки для карусели",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="planner/default.jpg",
                help_text="Загрузите изображение для поста",
                upload_to="blog/%Y/%m/%d",
                verbose_name="изображение",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="news_carousel",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="карусель новостей"
            ),
        ),
    ]
