# Generated by Django 4.0.1 on 2023-01-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_alt_text_post_carousel_link_text_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="news_carousel",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="карусель новостей"
            ),
        ),
    ]
