# Generated by Django 4.0.1 on 2023-01-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_news_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="main",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="для главной?"
            ),
        ),
    ]
