# Generated by Django 4.0.1 on 2022-01-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created",),
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "пункт заказа",
                "verbose_name_plural": "пункты заказа",
            },
        ),
    ]
